Megan walkthrough
SPAAM-community/wss-summer-school pull request #13
Opened 2022-10-04 16:53 UTC by meganemichel

2022-10-06 09:29 UTC, jfy133 requested changes
Content looks good, just some structural things, then I'll probably just add a pointer to the output docs indeed as you suggested... I pretty much just parroted what we had there...

2022-10-06 09:29 UTC, jfy133 commented on docs/2022/day-2.md
> +Once you have successfully cloned the repository, navigate to the directory `/wss-summer-school/docs/assets/data/2022/eager_tutorial`. This is the directory in which we will perform the following ana
We shouldn't do that (in case someone doesn't care about github), if the data is just the download script and the TSV file just have `wget` commands to download them from the repo instead.

2022-10-06 09:29 UTC, jfy133 commented on docs/2022/day-2.md
> +A **pipeline** is a series of linked computational steps, where the output of one process becomes the input of the next. Pipelines are critical for managing the huge quantities of data that are now b
[@] typo?

2022-10-06 09:29 UTC, jfy133 commented on docs/2022/day-2.md
> +A **pipeline** is a series of linked computational steps, where the output of one process becomes the input of the next. Pipelines are critical for managing the huge quantities of data that are now b
And maybe add a URL for Paleomix?

2022-10-06 09:29 UTC, jfy133 commented on docs/2022/day-2.md
> +<img src="https://github.com/SPAAM-community/wss-summer-school/raw/megan_walkthrough/docs/assets/slides/2022/2d-intro-to-nfcoreeager/eager2_metromap_complex.png">
Would be good to replace `megan_walkthrough` with `master` on all images (I know won't render before merge, but if we delete that branch it will be a problem :grimacing: )

2022-10-06 09:29 UTC, jfy133 commented on docs/2022/day-2.md
> +Briefly, nf-core/eager takes standard input file types that are shared across the genomics field, including raw fastq fiels, aligned reads in bam format, and a reference fasta. nf-core/eager can perf
```suggestion
Briefly, nf-core/eager takes standard input file types that are shared across the genomics field, including raw fastq files, aligned reads in bam format, and a reference fasta. nf-core/eager can perform preprocessing of this raw data, including adapter clipping, read merging, and quality control of adapter-trimmed data. Note that input files can be specified using wildcards OR a standardized tsv format file; the latter facilitates streamlined integration of multpile data types within a single EAGER run! More on this later.
```

2022-10-06 09:29 UTC, jfy133 commented on docs/2022/day-2.md
> +--run_bcftools_stats	// Generate variant calling statistics
ooof, shouldn't use `//` as comments in a bash command...

I would suggest including the the bash multiline `\` and then replace `//` with `#`

2022-11-14 15:22 UTC, meganemichel commented on docs/2022/day-2.md
> +Once you have successfully cloned the repository, navigate to the directory `/wss-summer-school/docs/assets/data/2022/eager_tutorial`. This is the directory in which we will perform the following ana
added `wget` commands.

2022-11-14 15:54 UTC, merged